language: node_js
node_js:
- lts/*
script:
- echo "nothing atm"
deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  bucket_name: dhis2-app-store-prod
  bucket_path: "_builds"
  access_key_id:
    secure: "UUy33x4U3v+VpOl1D547NSIqYZRxi3IhKota0V3hyQUigWlUJyaRERuLCmGpxBa28MXsjs7PTY3yManGkanwYJ79b5vO31stD1BzaAVRLooATSRQ/+nL0iFZIPUOzquy7Hr43OWR1hv/JQP2UnaDLCibj0W99me/L7JyPD16YzVbosGkqxWT3s1tW9sE+dwG6qekbsHLh2DMd2bI8QykCIup1ismHsbfX/x8HgJxnBcDg28dtydOYDCypt3v0c50FksFJaCmlwCDVrgkAi+HrbUtoA1r5B2N8AuMwEuq9liJlACy3lF02Q0gNovgFyXcHJHIUNJYp2oLdOlc1scqOBlfUfrp6KO/G6wbGm//nrKIXLLzSrNeKdfK2U9iACQptfM4gdK6e/6TZUvCefV1wbSCo0Wpiw1NZ4Dmbz7qdcwKwLubBvBRs+xEygZapS3n8DpnuDkm8+S+bufgEDH2wl3W/cAt1I4hSpvfKkEv6AIkh6yDdssvvYo3mUyI7ZhZMhBiiPHmjXfvBv+sRixrjEWUdeJa498HvbYSl+v7pczijxkGmYXAPTv77BgSq2GpNbPc72AqGvUUVsZUUUwtU2IOWreQvyoe+mf4QjByRZorcQp0amW7GfzHrSSNoZcSrwDzu8d4ViuxmapthpP6g5zij3ra5B8USUS7y8Y9cJk="
  secret_access_key:
    secure: "PMy2lpXcnoMIL08ZDQJWHBqregcqsVXB4Axt47NkyxzcLuBp8TUyBMIkIHantycXlkO/HVOYbeIEJwa44m0cGcKYqBxI5JLkXnlBGwXhVR+ErP/0fl9+N3DH1sf2wNZ8nP2KXuB7HA7r3fDy1f4Ys2+5mNID6VuSDTs34wP7BhIFLfQiLeEtLNg4KnreSsaLwcF9fAAplROoqHcqfVxApnwytW5/vlA1fLbjtKrrTBNiL9c96KKIOiR4B+bXAhws6CUhZZbwqK5R9tfOGrZkYIxTMTfCRQdc2leZDqJ7vyIwhYLBkGbAzlJEG2b534IlQHm/Nj47PvciOW/Py+3QMTDANZ4sxx9DVSlFnt9x3/7bU16bqVHV+2K654IcKnMQfsw9hO5w6DIFvWCVwj7yp4gM9TIaFe1dGSYO6jEGl0T6L6S3PVlPtTx+JJZdVxW0pdhW1MHl4mFsAs7gM1ZS1rLkDGnX7jYG6ld9dUqBJBfiEEVNR3xd6xhHio7irAsvH+ocEAHJYzkNrQ4XVB0EEBfxusgKt0vfwBfV2uYqPEcA+rhaLcjepHKv+8MG2beZXcKFPQpJGER3WlAHIyziXye8h34PbLe5HMNtYOWJzLXgjFT3vF6PZmCCh/psl9/oliIAwITivXS/MOGDKqOsoDzW75fqhVQArLGenNjmk/o="
  region: eu-west-1
  app: dhis2-app-store
  env: app-store-prod
  on:
    repo: dhis2/app-store
    tags: false
    branch: master
