version: 1

update_configs:
    - package_manager: 'javascript'
      directory: '/'
      update_schedule: 'weekly'
      version_requirement_updates: 'increase_versions'
      target_branch: 'next'
      automerged_updates:
          - match:
                dependency_name: '@dhis2/*'
                dependency_type: 'all'
                update_type: 'semver:minor'
          - match:
                dependency_type: 'all'
                update_type: 'semver:minor'
